# Generated by Django 6.0.4 on 2026-04-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('department', models.CharField(blank=True, choices=[('maths', 'Maths'), ('computer science', 'Computer Science'), ('commerce', 'Commerce'), ('zoology', 'Zoology'), ('botony', 'Botony'), ('statistics', 'Statistics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('english', 'English')], max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
