# Generated by Django 6.0.4 on 2026-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Admin123', max_length=100)),
                ('password', models.CharField(default='Admin123', max_length=100)),
            ],
        ),
    ]
