# Generated by Django 6.0.4 on 2026-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='number',
            field=models.CharField(default=847137829, max_length=100),
        ),
    ]
