# Generated by Django 6.0.4 on 2026-05-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='number',
            field=models.CharField(default='8471398761', max_length=100),
        ),
    ]
