# Generated by Django 6.0.4 on 2026-05-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='number',
        ),
    ]
